/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../common";
import type { Animal, AnimalInterface } from "../Animal";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b5060008060006101000a81548160ff021916908360000b60ff160217905550603f80603b6000396000f3fe6080604052600080fdfea264697066735822122087c4beefd69cdeff2bc7d645d3cb3ce90502822e4d3a8f76cadd58c3ebaf803364736f6c63430008110033";

type AnimalConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AnimalConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Animal__factory extends ContractFactory {
  constructor(...args: AnimalConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Animal> {
    return super.deploy(overrides || {}) as Promise<Animal>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Animal {
    return super.attach(address) as Animal;
  }
  override connect(signer: Signer): Animal__factory {
    return super.connect(signer) as Animal__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AnimalInterface {
    return new utils.Interface(_abi) as AnimalInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Animal {
    return new Contract(address, _abi, signerOrProvider) as Animal;
  }
}
