/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Animal__factory } from "./Animal__factory";
export { Bird__factory } from "./Bird__factory";
export { Dog__factory } from "./Dog__factory";
