/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface DogInterface extends utils.Interface {
  functions: {
    "bark()": FunctionFragment;
    "displayDogEnergy()": FunctionFragment;
    "eatDogFood()": FunctionFragment;
    "eatWater()": FunctionFragment;
    "run()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "bark"
      | "displayDogEnergy"
      | "eatDogFood"
      | "eatWater"
      | "run"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "bark", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "displayDogEnergy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "eatDogFood",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "eatWater", values?: undefined): string;
  encodeFunctionData(functionFragment: "run", values?: undefined): string;

  decodeFunctionResult(functionFragment: "bark", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "displayDogEnergy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "eatDogFood", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "eatWater", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "run", data: BytesLike): Result;

  events: {};
}

export interface Dog extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DogInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    bark(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    displayDogEnergy(overrides?: CallOverrides): Promise<[number]>;

    eatDogFood(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    eatWater(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    run(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  bark(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  displayDogEnergy(overrides?: CallOverrides): Promise<number>;

  eatDogFood(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  eatWater(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  run(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    bark(overrides?: CallOverrides): Promise<void>;

    displayDogEnergy(overrides?: CallOverrides): Promise<number>;

    eatDogFood(overrides?: CallOverrides): Promise<void>;

    eatWater(overrides?: CallOverrides): Promise<void>;

    run(overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    bark(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    displayDogEnergy(overrides?: CallOverrides): Promise<BigNumber>;

    eatDogFood(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    eatWater(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    run(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    bark(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    displayDogEnergy(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    eatDogFood(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    eatWater(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    run(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
