/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Animal } from "./Animal";
export type { Bird } from "./Bird";
export type { Dog } from "./Dog";
export * as factories from "./factories";
export { Animal__factory } from "./factories/Animal__factory";
export { Bird__factory } from "./factories/Bird__factory";
export { Dog__factory } from "./factories/Dog__factory";
